# Generated by Django 6.0.3 on 2026-03-14 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assetowner',
            fields=[
                ('ownerid', models.AutoField(db_column='OwnerID', primary_key=True, serialize=False)),
                ('ownername', models.CharField(db_column='OwnerName', max_length=100)),
                ('department', models.CharField(blank=True, db_column='Department', max_length=100, null=True)),
                ('contactemail', models.CharField(blank=True, db_column='ContactEmail', max_length=100, null=True)),
            ],
            options={
                'db_table': 'AssetOwner',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('scanid', models.AutoField(db_column='ScanID', primary_key=True, serialize=False)),
                ('scandate', models.DateTimeField(db_column='ScanDate')),
                ('scannername', models.CharField(blank=True, db_column='ScannerName', max_length=100, null=True)),
                ('scantype', models.CharField(blank=True, db_column='ScanType', max_length=50, null=True)),
                ('scope', models.CharField(blank=True, db_column='Scope', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Scan',
            },
        ),
        migrations.CreateModel(
            name='Vulnerabilitydefinition',
            fields=[
                ('vuldefid', models.AutoField(db_column='VulDefID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('cve_id', models.CharField(blank=True, db_column='CVE_ID', max_length=20, null=True, unique=True)),
                ('basescore', models.DecimalField(blank=True, db_column='BaseScore', decimal_places=1, max_digits=3, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'VulnerabilityDefinition',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('assetid', models.AutoField(db_column='AssetID', primary_key=True, serialize=False)),
                ('hostname', models.CharField(db_column='Hostname', max_length=255)),
                ('ipaddress', models.CharField(blank=True, db_column='IPAddress', max_length=45, null=True)),
                ('operatingsystem', models.CharField(blank=True, db_column='OperatingSystem', max_length=100, null=True)),
                ('isactive', models.IntegerField(blank=True, db_column='IsActive', null=True)),
                ('ownerid', models.ForeignKey(db_column='OwnerID', on_delete=django.db.models.deletion.CASCADE, to='vams_application.assetowner')),
            ],
            options={
                'db_table': 'Asset',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('findingid', models.AutoField(db_column='FindingID', primary_key=True, serialize=False)),
                ('discoverydate', models.DateField(blank=True, db_column='DiscoveryDate', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=14, null=True)),
                ('assetid', models.ForeignKey(db_column='AssetID', on_delete=django.db.models.deletion.CASCADE, to='vams_application.asset')),
                ('scanid', models.ForeignKey(db_column='ScanID', on_delete=django.db.models.deletion.CASCADE, to='vams_application.scan')),
                ('vuldefid', models.ForeignKey(db_column='VulDefID', on_delete=django.db.models.deletion.CASCADE, to='vams_application.vulnerabilitydefinition')),
            ],
            options={
                'db_table': 'Finding',
            },
        ),
        migrations.CreateModel(
            name='Mitigationaction',
            fields=[
                ('mactionid', models.AutoField(db_column='MActionID', primary_key=True, serialize=False)),
                ('actiondate', models.DateTimeField(blank=True, db_column='ActionDate', null=True)),
                ('actiontaken', models.TextField(blank=True, db_column='ActionTaken', null=True)),
                ('operatorname', models.CharField(blank=True, db_column='OperatorName', max_length=100, null=True)),
                ('findingid', models.ForeignKey(db_column='FindingID', on_delete=django.db.models.deletion.CASCADE, to='vams_application.finding')),
            ],
            options={
                'db_table': 'MitigationAction',
            },
        ),
    ]
